import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const printProjectReport = async (projectName: string, docs: { prd: string, srs: string, logs: string }) => {
  const doc = new jsPDF();
  
  // Title Page
  doc.setFontSize(22);
  doc.text(`${projectName} - Project Report`, 20, 30);
  doc.setFontSize(12);
  doc.text(`Generated by Antigravity AI Lab`, 20, 40);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 50);

  // PRD Section
  doc.addPage();
  doc.setFontSize(18);
  doc.text("1. Product Requirement Document (PRD)", 20, 20);
  doc.setFontSize(10);
  const prdLines = doc.splitTextToSize(docs.prd, 170);
  doc.text(prdLines, 20, 30);

  // SRS & Logs... (Similarly add more pages)
  
  // Save the PDF
  doc.save(`${projectName}_Final_Report.pdf`);
};