"use client";
import { motion } from 'framer-motion';

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#f4f1ea] pt-40 pb-20 px-6 font-mono text-[#1a1a1a]">
      <div className="max-w-4xl mx-auto">
        
        {/* Top Header Label */}
        <div className="flex justify-between items-center mb-4 px-2">
          <span className="text-[10px] font-black bg-black text-white px-2 py-1 uppercase">Top Secret</span>
          <span className="text-[10px] font-bold opacity-40 uppercase">File_Ref: PRIVACY-00-ALPHA</span>
        </div>

        <div className="border-t-8 border-black pt-10 relative overflow-hidden">
          {/* Subtle Folder Texture */}
          <div className="absolute inset-0 opacity-[0.02] pointer-events-none bg-[url('https://www.transparenttextures.com/patterns/pinstripe.png')]" />

          <h1 className="text-5xl md:text-7xl font-black uppercase tracking-tighter mb-10 italic">
            Privacy <br /> Protocol.
          </h1>

          <div className="space-y-12 text-sm leading-relaxed relative z-10">
            
            {/* Section 1 */}
            <section className="border-l-2 border-black pl-6">
              <h2 className="text-xl font-black uppercase mb-4 underline italic">01. Data Extraction</h2>
              <p className="font-bold uppercase tracking-tight">
                Hum aapka data extract karte hain taaki system sync rahe. Isme aapka 
                <span className="bg-black text-black hover:bg-transparent hover:text-red-600 transition-all cursor-help px-1 mx-1">IP ADDRESS</span>, 
                <span className="bg-black text-black hover:bg-transparent hover:text-red-600 transition-all cursor-help px-1 mx-1">GEOLOCATION</span> 
                aur browser fingerprints shamil hain. 
              </p>
              <p className="mt-4 text-[10px] opacity-60 font-black italic underline cursor-help">
                [HOVER OVER BLACK BARS TO DECLASSIFY INFORMATION]
              </p>
            </section>

            {/* Section 2 */}
            <section className="border-l-2 border-black pl-6">
              <h2 className="text-xl font-black uppercase mb-4 underline italic">02. Neural Storage</h2>
              <p className="font-bold uppercase tracking-tight">
                Aapka code <span className="italic underline">ephemeral containers</span> mein store hota hai. 
                Session terminate hote hi, data ko 
                <span className="bg-black text-black hover:bg-transparent hover:text-red-600 transition-all cursor-help px-1 mx-1">PERMANENTLY VAPORIZED</span> 
                kar diya jata hai, jab tak aap manual save na karein.
              </p>
            </section>

            {/* Section 3 */}
            <section className="border-l-2 border-black pl-6">
              <h2 className="text-xl font-black uppercase mb-4 underline italic">03. Third-Party Links</h2>
              <p className="font-bold uppercase tracking-tight">
                CodeMapers kisi bhi <span className="italic underline">External Intelligence</span> ke saath data share nahi karta, 
                sivaaye un nodes ke jo aapke workspace ko power dete hain. Hum 
                <span className="bg-black text-black hover:bg-transparent hover:text-red-600 transition-all cursor-help px-1 mx-1">NO SURVEILLANCE</span> 
                policy follow karte hain.
              </p>
            </section>

          </div>

          {/* Footer Clearance */}
          <div className="mt-20 border-t-2 border-black pt-8 flex justify-between items-start">
            <div className="text-[10px] font-black uppercase max-w-xs">
              This document is auto-generated by the CodeMapers Legal Engine. 
              Unauthorized duplication is a violation of the mesh-net laws.
            </div>
            <div className="flex flex-col items-end">
               <div className="w-32 h-12 bg-black flex items-center justify-center text-[#f4f1ea] font-black text-xs uppercase rotate-2">
                 Approved
               </div>
               <span className="text-[8px] mt-2 font-mono">STAMP_ID: 992-KLR</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}